## Numpy package:
1. numericsl data
2. computations 

In [7]:
import numpy as np

### Difference between numpy and list:
1. less memory
2. faster
3. convenient

In [9]:
#1-dimensional array

a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:

a1.shape

(3, 3)

In [12]:
a1.ndim

2

In [13]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2)
print(a2.shape[0])
print(a2.shape[1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
4
3


In [14]:
a3=np.array([],dtype="int32")

In [18]:
a3=np.append(a3,int(input()))
a3

12


array([23, 34, 45, 56, 67, 12])

In [19]:
a3=np.append(a3,[23,34,45,56,67])
a3

array([23, 34, 45, 56, 67, 12, 23, 34, 45, 56, 67])

In [20]:
a2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### slicing:


In [21]:
print(a3[3])

56


In [22]:
print(a2[1,1])

5


In [23]:
print(a2[3,2])

12


In [24]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [25]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


In [26]:
print(a2[0,0:2])

[1 2]


# lterate through array:


In [27]:
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [28]:
list1=[[1,2],[3,4]]
for i in list1:
    print(i)

[1, 2]
[3, 4]


In [29]:
for ele in a2.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [30]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## indexing with boolean array


In [31]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [33]:
result = (arr1 % 2 == 0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [34]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# appending array

In [35]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))  ## vertical stacking

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [36]:
print(np.hstack((arr1,arr2))) ## horizontal stacking

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes:
1. size()
2. itemsize()
3. dtype()
4. ndim()
5. shape()
6. arrange()
7. reshape()
8. ravel()

In [37]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [38]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


### Functions:
1. zeros()
2. ones()
3. full()

In [39]:
o = np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
i = np.zeros((2,3),dtype="int32")
i

array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
f = np.full((3,3),"nihith")
f

array([['nihith', 'nihith', 'nihith'],
       ['nihith', 'nihith', 'nihith'],
       ['nihith', 'nihith', 'nihith']], dtype='<U6')

In [42]:
#eye()
e = np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
#linspace()--> linear spacing elements
l = np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [44]:
#raval()
print(np.array(a.flat))
print(a.ravel())

[1 2 3 4 5]
[1 2 3 4 5]


## function:
1. min()
2. max()
3. sum()
4. sqrt()
5. mean()
6. median()
7. std()


In [46]:
print(a1.max())
print(a1.min())

9
1


In [47]:
a1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
print(a1.sum())#sum of all elements
print(a1.sum(axis=1))#sum of row elements
print(a1.sum(axis=0))#sum of coloumn elements

45
[ 6 15 24]
[12 15 18]


# Mathematical Operations:+,-,*,/,%

In [49]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)

[12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]



# dot()-->Matrix multiplication¶
## arr1=m X n
### arr2=n X l

In [50]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr1.dot(arr2)


array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [51]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
#Transpose of an array
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])


# Applying user-defined function:

In [53]:
list1=list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [54]:

a=np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [55]:
#1/(1+1)-->x/(x+1)
result=[x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [56]:
f=np.vectorize(lambda x : x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])