In [4]:
from numpy import random
print(random.randint(1,100))#random integer in the gievn range
print(random.rand())#float 0-1

84
0.5330595167922166


In [5]:
# creating n-dimensional array with random values

print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[ 1 61 21]
[[63  3  9 80]
 [82 93 59 94]
 [59 42  5 38]]
[[[76  2]
  [24 45]
  [57 18]
  [ 8 28]]

 [[15  1]
  [53 62]
  [22  1]
  [99 68]]

 [[19 34]
  [95 63]
  [26 27]
  [69 82]]]


In [6]:
print(random.rand())
print(random.rand(2))
print(random.rand(2,3))

0.6701392606379584
[0.79566803 0.58397315]
[[0.89958247 0.75915011 0.8813827 ]
 [0.17563043 0.16954161 0.05620755]]


In [7]:
a= random.randint(100,size=(3)).ravel() #flat
a

array([84, 15, 99])

In [8]:
random.choice(a)

84

In [9]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(3,4))

array([[3, 2, 1, 2],
       [1, 3, 3, 1],
       [2, 4, 2, 3]])

### pandas:
1. data manipulation,analysis and cleaning
2. tabular,unlabelled


### creating a data frame
1. using 2 dictionaries
2. simple dicionary-->dataframe
3. using series


In [10]:

import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"first":dict1,"second":dict2}
df = pd.DataFrame(data)
df

first  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [11]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'f':9}
data = {"first":dict1,"second":dict2}
df = pd.DataFrame(data)
df

first  second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0

In [12]:
# simple dicionary-->dataframe
d1 = {"name":["nihith","nani","pichi"],"address":["hyd","wgl","goa"]}
df1 = pd.DataFrame(d1)
df1

name address
0  nihith     hyd
1    nani     wgl
2   pichi     goa

In [13]:
# using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([11.1,12.2,13.3,14.4,15.5,16.6,17.7,18.8,19.0,20.0])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"a":s1,"aa":s2,"aaa":s3}
df3 = pd.DataFrame(data)
df3

a    aa aaa
0   1  11.1   a
1   2  12.2   b
2   3  13.3   c
3   4  14.4   d
4   5  15.5   e
5   6  16.6   f
6   7  17.7   g
7   8  18.8   h
8   9  19.0   i
9  10  20.0   j

# selecting the data from the dataframe
1. loc
2. iloc

In [14]:
df3["a"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: a, dtype: int64

In [15]:
df3[["a","aa"]]

a    aa
0   1  11.1
1   2  12.2
2   3  13.3
3   4  14.4
4   5  15.5
5   6  16.6
6   7  17.7
7   8  18.8
8   9  19.0
9  10  20.0

In [16]:
# single colum
df3.loc[:,"a"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: a, dtype: int64

In [17]:
#extracting multipule colum
df3.loc[0:5,["a","aa"]]

a    aa
0  1  11.1
1  2  12.2
2  3  13.3
3  4  14.4
4  5  15.5
5  6  16.6

In [18]:
df3.iloc[:,1]

0    11.1
1    12.2
2    13.3
3    14.4
4    15.5
5    16.6
6    17.7
7    18.8
8    19.0
9    20.0
Name: aa, dtype: float64


# Retrieving the information of DataFrame


In [19]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       10 non-null     int64  
 1   aa      10 non-null     float64
 2   aaa     10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [20]:
df3.shape

(10, 3)

In [21]:
df3.columns

Index(['a', 'aa', 'aaa'], dtype='object')

In [22]:
df3.index

RangeIndex(start=0, stop=10, step=1)


# Viewing data from DataFrame:¶
1. head()
2. tail()
3. sample()

In [23]:
#First 5 rows
df3.head()

a    aa aaa
0  1  11.1   a
1  2  12.2   b
2  3  13.3   c
3  4  14.4   d
4  5  15.5   e

In [24]:
df3.head(3)

a    aa aaa
0  1  11.1   a
1  2  12.2   b
2  3  13.3   c

In [25]:
df3.tail()

a    aa aaa
5   6  16.6   f
6   7  17.7   g
7   8  18.8   h
8   9  19.0   i
9  10  20.0   j

In [26]:
df3.tail(4)

a    aa aaa
6   7  17.7   g
7   8  18.8   h
8   9  19.0   i
9  10  20.0   j

In [27]:
#Selects random data
df3.sample()

a    aa aaa
5  6  16.6   f

In [28]:
df3.sample(6)

a    aa aaa
6   7  17.7   g
0   1  11.1   a
5   6  16.6   f
9  10  20.0   j
2   3  13.3   c
3   4  14.4   d

In [29]:
df3.describe()

a         aa
count  10.00000  10.000000
mean    5.50000  15.860000
std     3.02765   3.063114
min     1.00000  11.100000
25%     3.25000  13.575000
50%     5.50000  16.050000
75%     7.75000  18.525000
max    10.00000  20.000000

In [31]:
#Renaming the column headers
df3 = df3.rename(columns={"a":"First","aa":"Second","aaa":"Third"})
df3

First  Second Third
0      1    11.1     a
1      2    12.2     b
2      3    13.3     c
3      4    14.4     d
4      5    15.5     e
5      6    16.6     f
6      7    17.7     g
7      8    18.8     h
8      9    19.0     i
9     10    20.0     j